### ISSUE TITLE
problem with step 1

### ISSUE THREAD

**Issue by IreneC1** [SAP-samples/btp-sac-forecast#3]
Hello, 
I am interested in the tutorial for the btp-sac-forecast.
The step 1 is to verify all the access and make sure all the prerequisite are good to go.
In the:
"2. Prerequisites for SAP BTP
Enable SAP BTP Cloud Foundry [global account](https://developers.sap.com/tutorials/cp-cf-entitlements-add.html)."
By going to the link in "global account" i am sent to a page saying that the tutorial could not be found. What can i do next ?
Thank you

**Comment by Kaderde** [comment]
Hi,

Thank you for reaching out.

It appears that the previous link has been removed. Please try the new one: 
https://developers.sap.com/tutorials/prepare-btp-cf.html.

I will update the link on the page accordingly.

Best regards,
Abdelkader
